# Logistic Regression
The nice thing of regression is that the model itself will give us a fair indication of which variables are important for the analysis and which are not

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('udemy_data/tableu/preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of the week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Create a target 
- We want classes the employee base on the Absenteeism Time in Hour (ath)
- If hth <= median, that is normal (0) else is not normal (1)
- The reason why we use median is by using the median we have implicitly balance the dataset roughly half of the targets

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
#np.whare(condition, value_if_true, value_if_false)
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] >
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
#add the result to the data frame
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of the week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [7]:
#prove 1
data_preprocessed['Excessive Absenteeism'].value_counts()

0    381
1    319
Name: Excessive Absenteeism, dtype: int64

In [8]:
#prove 2, 45,5% labeled 1 and 54,5% labeled 0. 
targets.sum()/targets.shape[0]*100

45.57142857142858

### Checkpoint 

In [9]:
#before get the correlation
#becase we already create "Excessive Absenteeism", we need drop "Absenteeism Time in Jours"
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of the week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [26]:
#new data_with_targets after get the correlation (implement backward elimination)
#drop  Distance to Work, Month, Daily Work Load Average
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Distance to Work', 'Month', 'Daily Work Load Average'], axis=1)
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Day of the week  \
0         0         0         0         1                1   
1         0         0         0         0                1   
2         0         0         0         1                2   
3         1         0         0         0                3   
4         0         0         0         1                3   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## Select the inputs of  the Regression 

In [27]:
#iloc[row, column]
unscaled_inputs = data_with_targets.iloc[:, :-1]
unscaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Day of the week  \
0         0         0         0         1                1   
1         0         0         0         0                1   
2         0         0         0         1                2   
3         1         0         0         0                3   
4         0         0         0         1                3   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                     289   33               30          0         2     1  
1                     118   50               31          0         1     0  
2                     179   38               31          0         0     0  
3                     279   39               24          0         2     0  
4                     289   33               30          0         2     1

## Standardized the data 
- In this case, we need to scale unscaled_inputs, but without include the reason feature. Use the function Customer scaller 

In [28]:
#this code is used for scaled all the data
# from sklearn.preprocessing import StandardScaler
# scale = StandardScaler()
# scale.fit(unscaled_inputs)

# scaled_inputs = scale.transform(unscaled_inputs)
# scaled_inputs

In [29]:
#with the code above, we will standarize all the data include dummy. But we don't want because the main
#reason information gonna be loss, so we need to make custome standardization
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin

class CustomerScaler(BaseEstimator, TransformerMixin):
    def __init__(self, columns, copy=True, with_mean=True, with_std= True):
        self.scaler = StandardScaler(copy, with_mean, with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [30]:
#our CustomerScaler function needs the column's name that want to scaled, so we need to declare it first
unscaled_inputs.columns

Index(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Day of the week',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'],
      dtype='object')

In [31]:
#choose the column (before backward elimination)
# column_to_scale = ['Month','Day of the week', 'Transportation Expense', 'Distance to Work', 'Age',
#        'Daily Work Load Average', 'Body Mass Index', 'Children','Pets']

#after backward elimination implemented
column_to_scale = ['Day of the week', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Children','Pets']
#start to scale the data
absenteeism_scaler = CustomerScaler(column_to_scale)

In [32]:
#see the results, the reasons and educations columns do not scale
absenteeism_scaler.fit(unscaled_inputs)

scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Day of the week  \
0         0         0         0         1        -0.800950   
1         0         0         0         0        -0.800950   
2         0         0         0         1        -0.232900   
3         1         0         0         0         0.335149   
4         0         0         0         1         0.335149   

   Transportation Expense       Age  Body Mass Index  Education  Children  \
0                1.005844 -0.536062         0.767431          0  0.880469   
1               -1.574681  2.130803         1.002633          0 -0.019280   
2               -0.654143  0.248310         1.002633          0 -0.919030   
3                0.854936  0.405184        -0.643782          0  0.880469   
4                1.005844 -0.536062         0.767431          0  0.880469   

       Pets  
0  0.268487  
1 -0.589690  
2 -0.589690  
3 -0.589690  
4  0.268487

## Split the data 

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(scaled_inputs, targets, test_size=0.2, random_state= 27)

## Build Model Using Logistic Regression

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [35]:
model.score(X_train, y_train)

0.7982142857142858

## Get the intercept and coefficient 

In [36]:
model.intercept_

array([-1.85154706])

In [37]:
model.coef_

array([[ 3.10854009,  1.24076606,  2.99650257,  0.76045607, -0.17041826,
         0.72823526, -0.39100005,  0.39731646,  0.06444061,  0.44497442,
        -0.39769706]])

In [38]:
unscaled_inputs.columns

Index(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Day of the week',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'],
      dtype='object')

In [39]:
summary_table = pd.DataFrame(columns=['Feature Name'], data = unscaled_inputs.columns)
summary_table['Coef'] = np.transpose(model.coef_)
summary_table.sort_values(by=['Coef'], ascending=False)

Feature Name      Coef
0                 Reason_1  3.108540
2                 Reason_3  2.996503
1                 Reason_2  1.240766
3                 Reason_4  0.760456
5   Transportation Expense  0.728235
9                 Children  0.444974
7          Body Mass Index  0.397316
8                Education  0.064441
4          Day of the week -0.170418
6                      Age -0.391000
10                    Pets -0.397697

In [40]:
#add intercept values to the list
summary_table.index = summary_table.index+1
summary_table.loc[0] = ['Intercept', model.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name      Coef
0                Intercept -1.851547
1                 Reason_1  3.108540
2                 Reason_2  1.240766
3                 Reason_3  2.996503
4                 Reason_4  0.760456
5          Day of the week -0.170418
6   Transportation Expense  0.728235
7                      Age -0.391000
8          Body Mass Index  0.397316
9                Education  0.064441
10                Children  0.444974
11                    Pets -0.397697

In [41]:
#when we dealing with logistic regression, the coefficient we are predicting called log(odds), 
#in logistic regression, the log(odds) transform to 0 and 1
#log(odds) = bias(intercept) + coef1.x1+ coef2.x2 +  ... + coefn.xn
#to make them more interpretable, let's find the exponentials of these coefficients

summary_table['Odds_ratio'] = np.exp(summary_table['Coef'])
summary_table

Feature Name      Coef  Odds_ratio
0                Intercept -1.851547    0.156994
1                 Reason_1  3.108540   22.388336
2                 Reason_2  1.240766    3.458262
3                 Reason_3  2.996503   20.015412
4                 Reason_4  0.760456    2.139252
5          Day of the week -0.170418    0.843312
6   Transportation Expense  0.728235    2.071422
7                      Age -0.391000    0.676380
8          Body Mass Index  0.397316    1.487827
9                Education  0.064441    1.066562
10                Children  0.444974    1.560450
11                    Pets -0.397697    0.671866

In [42]:
#The further away from 0 a coefficient is, the bigger its importance  
summary_table.sort_values(by=['Odds_ratio'], ascending = False)

Feature Name      Coef  Odds_ratio
1                 Reason_1  3.108540   22.388336
3                 Reason_3  2.996503   20.015412
2                 Reason_2  1.240766    3.458262
4                 Reason_4  0.760456    2.139252
6   Transportation Expense  0.728235    2.071422
10                Children  0.444974    1.560450
8          Body Mass Index  0.397316    1.487827
9                Education  0.064441    1.066562
5          Day of the week -0.170418    0.843312
7                      Age -0.391000    0.676380
11                    Pets -0.397697    0.671866
0                Intercept -1.851547    0.156994

# Backward elimination
- The idea is that we can simplify our model by removing all features which have close to no contribution to the model (close to 0).
- back to our previous variable, data_with_targets but drop some feature like Distance to Work, Month, Daily Work Load Average

# Test the model

In [43]:
#our model is overfit, we need re-preprocess our model
model.score(X_test, y_test)

0.6071428571428571

In [46]:
#left mean 0, right mean 1
predict_proba = model.predict_proba(X_test)
predict_proba

array([[0.77178037, 0.22821963],
       [0.22679487, 0.77320513],
       [0.22679487, 0.77320513],
       [0.93089977, 0.06910023],
       [0.55842026, 0.44157974],
       [0.80260709, 0.19739291],
       [0.76982293, 0.23017707],
       [0.80233042, 0.19766958],
       [0.51356087, 0.48643913],
       [0.77178037, 0.22821963],
       [0.38561599, 0.61438401],
       [0.88735284, 0.11264716],
       [0.43237539, 0.56762461],
       [0.43237539, 0.56762461],
       [0.85490035, 0.14509965],
       [0.85807192, 0.14192808],
       [0.68877231, 0.31122769],
       [0.73590255, 0.26409745],
       [0.83125328, 0.16874672],
       [0.83280178, 0.16719822],
       [0.05622509, 0.94377491],
       [0.81888472, 0.18111528],
       [0.59359528, 0.40640472],
       [0.46109567, 0.53890433],
       [0.7077247 , 0.2922753 ],
       [0.04708935, 0.95291065],
       [0.84462284, 0.15537716],
       [0.91735813, 0.08264187],
       [0.27945625, 0.72054375],
       [0.91420324, 0.08579676],
       [0.

In [47]:
predict_proba.shape

(140, 2)

In [52]:
#get the 1 value
predict_proba[:,1]

array([0.22821963, 0.77320513, 0.77320513, 0.06910023, 0.44157974,
       0.19739291, 0.23017707, 0.19766958, 0.48643913, 0.22821963,
       0.61438401, 0.11264716, 0.56762461, 0.56762461, 0.14509965,
       0.14192808, 0.31122769, 0.26409745, 0.16874672, 0.16719822,
       0.94377491, 0.18111528, 0.40640472, 0.53890433, 0.2922753 ,
       0.95291065, 0.15537716, 0.08264187, 0.72054375, 0.08579676,
       0.53890433, 0.29086391, 0.10033596, 0.332349  , 0.19591823,
       0.76374225, 0.51477732, 0.70027525, 0.73927831, 0.37520765,
       0.72054375, 0.22921004, 0.29086391, 0.10033596, 0.20215129,
       0.19766958, 0.12269252, 0.98037912, 0.18251164, 0.81210175,
       0.07559309, 0.19766958, 0.79440538, 0.41354841, 0.8254472 ,
       0.93888251, 0.72657066, 0.2721845 , 0.54668755, 0.2457173 ,
       0.18111528, 0.81945794, 0.91801347, 0.19766958, 0.18109454,
       0.25259798, 0.2922753 , 0.23476283, 0.22911706, 0.51444116,
       0.38979342, 0.7202027 , 0.22560767, 0.13162728, 0.67419

# Save our model

In [53]:
import pickle

In [54]:
with open('model', 'wb') as file: #file_name, write byte for write to file
    pickle.dump(model, file) #model we have builed, file

In [55]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)